watch:
  directories:
    - site
    - tests
    - src
  fileMask: '*.php'
notifications:
  passingTests: false
  failingTests: false
phpunit:
  binaryPath: './vendor/bin/phpunit'
  arguments: '--configuration=./.phpunit.xml --colors=always ./tests/'
