watch:
  directories:
    - config
    - site
    - src
    - tests
  fileMask: "*.php"
notifications:
  passingTests: false
  failingTests: false
phpunit:
  binaryPath: "./vendor/bin/phpunit"
  arguments: "--configuration=./.phpunit.xml --colors=always ./tests/"
