title: Default Page

tabs:
  content:
    icon: text
    label: Content
    preset: page
    fields:
      description:
        label: Description
        type: text
      text:
        label: Text
        type: textarea
        size: large

  seotab: seo
