title: Content

options:
  changeTitle: true

columns:
  left:
    width: 1/2
    sections:
      pages:
        label: Pages
        status: all
  right:
    width: 1/2
    fields:
      address:
        label: Address
          fr: Adresse
        type: writer
        inline: true
      email:
        label: Email
        type: email
      linkedin:
        icon: linkedin
        label: LinkedIn
        placeholder: 'https://www.linkedin.com/in/benjaminhaeberli/'
        translate: false
        type: url
      github:
        icon: github
        label: GitHub
        placeholder: 'github.com/benjaminhaeberli'
        translate: false
        type: url
